class{ 'puppet::passenger':
  puppet_passenger_port         => '8140',
  puppet_passenger_ssl_protocol => 'TLSv1.2',
  puppet_passenger_ssl_cipher   => 'AES256+EECDH:AES256+EDH',
  puppet_docroot                => '/etc/puppet/doc',
  apache_serveradmin            => 'me@example.com',
  puppet_site                   => 'master.example.com',
  puppet_conf                   => '/etc/puppet/puppet.conf',
  puppet_ssldir                 => '/var/lib/puppet/ssl',
  certname                      => 'master.example.com',
  passenger_max_pool_size       => '4',
  passenger_high_performance    => true,
  passenger_max_requests        => '1000',
  passenger_stat_throttle_rate  => '30',
}
